### ISSUE TITLE
Dashboard icon

### ISSUE THREAD

**Issue by K-Kumar-01** [king-11/Nuxt_Images#1]
the dashboard icon on sidebar is not a link .
in my opinion that should also be made a link.
also signup feature is not there.
Furthermore a readme containig what this project is would be useful

**Comment by king-11** [comment]
Actually for dashboard it's a typo instead of ' ' it will be '/' in next commit also as such register feature is there if you visit /register. It's just that linking hasn't been done yet.

**Comment by K-Kumar-01** [comment]
thanks for the clarification.
just upadte the readme so that people can know what it is. It would be of real help
